version: '3.8'
services:
  dev-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=booking
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    networks:
      - nestjs-net

  test-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27018:27017
    networks:
      - nestjs-net
networks:
  nestjs-net:
